language: php

env:
  global:
    - COMPOSER_FLAGS="" PHPCS=0

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.3
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest" PHPCS=1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - if [[ "$PHPCS" == "1" ]]; then composer run phpcs ; fi
  - composer run phpunit
